[package]
name = "lodger-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
ipnet = "2.12.2"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
uuid = { version = "1.26.1", features = ["serde"] }

[dev-dependencies]
serde_json = "=1.0.151"

[lints]
workspace = true
